[project]
name = "ops_pilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "herohit", email = "rohitnegi323@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.14.0",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
ops_pilot = "ops_pilot:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
